### ISSUE TITLE
Grammar corrections on the main page

### ISSUE THREAD

**Issue by venkateshprabhu2** [18praneeth/sushiksha-website#5]
- 170 Mentee should be 170 Mentees

- 20 Mentor should be 20 Mentors

- 'An a interactive platform....' should simply be 'An interactive platform.....'. Also, G & M should not be capitals in the 'Growth Mindset' at the end of the sentence.

**Comment by sskini2** [comment]
In about Sushiksha: Lets expand the first mentions of VKSSF and VAA and link it to its website. Please see the re-written version

"Sushiksha Mentoring Program is organized for scholars of Vishwa Konkani Student Scholarship Fund (VKSSF) by members of VKSSF Alumni Association(VAA). Sushiksha was started in 2018 by Royal Denzil Sequeira, a member of VAA since 2015, with 20 mentees. Since then Sushiksha.. "
